### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/hc/core5/http/ClassicHttpRequest after upgrading to 4.4.1

### ISSUE THREAD

**Issue by gregma** [bonigarcia/webdrivermanager#637]
Description of the problem: Getting the above when trying to use the webDriverManager

Browser and version: Microsoft Edge 42

Operating system: Windows 10

WebDriverManager version: 4.2.2

WebDriverManager use:

`
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
<maven-compiler-plugin.version>3.8.0</maven-compiler-plugin.version>
<maven-resources-plugin.version>3.0.1</maven-resources-plugin.version>
<maven-source-plugin.version>3.0.1</maven-source-plugin.version>
<exec-maven-plugin.version>1.6.0</exec-maven-plugin.version>
<appium.version>7.0.0</appium.version>
<commons-io.version>2.6</commons-io.version>
<commons-text.version>1.6</commons-text.version>
<db2jcc4.version>4.21.29</db2jcc4.version>
<edgegrid.version>4.0.0</edgegrid.version>
<guava.version>27.1-jre</guava.version>
<httpclient.version>4.5.13</httpclient.version>
<ini4j.version>0.5.4</ini4j.version>
<jna.version>5.2.0</jna.version>
<jtds.version>1.3.1</jtds.version>
<log4j.version>2.11.2</log4j.version>
<mssql.version>8.4.1</mssql.version>
<ojdbc6.version>11.1.0.7.0</ojdbc6.version>
<opencsv.version>4.5</opencsv.version>
<oshi-core.version>3.13.0</oshi-core.version>
<rest-assured.version>3.3.0</rest-assured.version>
<selenium-java.version>3.141.59</selenium-java.version>
<testng.version>6.14.3</testng.version>
<vlcj.version>3.12.1</vlcj.version>
<webdrivermanager.version>4.4.1</webdrivermanager.version>

            WebDriverManager.edgedriver().setup();
            WebDriverManager.edgedriver().clearDriverCache();
            WebDriverManager.edgedriver().clearResolutionCache();
            EdgeDriverService edgeDriverService = new EdgeDriverService.Builder().usingAnyFreePort().build();
            wDriver = new EdgeDriver(edgeDriverService, options);
            wDriver.manage().window().maximize();
            ((JavascriptExecutor) wDriver).executeScript("document.body.style.zoom='100%';");
`

WebDriverManager traces:

`04-27-2021 08:24:39 [main] INFO framework.Log - Entering method DriverFactory::getDriver() with

{tab=bd, browserVersion=latest, browserName=MicrosoftEdge}
04-27-2021 08:24:39 [main] DEBUG framework.Log - tab:bd
04-27-2021 08:24:39 [main] DEBUG framework.Log - browserVersion:latest
04-27-2021 08:24:39 [main] DEBUG framework.Log - browserName:MicrosoftEdge
04-27-2021 08:24:39 [main] INFO framework.Log -
capabilities.setCapability(browserName, "MicrosoftEdge")
capabilities.setCapability(browserVersion, "latest")
capabilities.setCapability(tab, "bd")
04-27-2021 08:24:39 [main] INFO framework.Log - Edge Application Name from Registry was: @{Microsoft.MicrosoftEdge_42.17134.1098.0_neutral__8wekyb3d8bbwe?ms-resource://Microsoft.MicrosoftEdge/Resources/AppName}
04-27-2021 08:24:39 [main] INFO framework.Log - Edge Application Version is: 42
`
Error trace:
`
java.lang.NoClassDefFoundError: org/apache/hc/core5/http/ClassicHttpRequest

at framework.DriverFactory.getDriver(DriverFactory.java:431)
at tests.BaseTest.launchDriver(BaseTest.java:1294)
at tests.BaseTest.beforeSuite(BaseTest.java:954)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: java.lang.ClassNotFoundException: org.apache.hc.core5.http.ClassicHttpRequest
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 22 more`
