### ISSUE TITLE
Webdrivermanager 1.4.9 not working with Selenium 3.0.0-beta4

### ISSUE THREAD

**Issue by thomPersson** [bonigarcia/webdrivermanager#64]
When upgrading to Selenium 3.0.0-beta4 it fails to start the drivers with the following exception:

```
java.lang.NoClassDefFoundError: org/openqa/selenium/ElementNotSelectableException
        at org.openqa.selenium.remote.ErrorCodes.<clinit>(ErrorCodes.java:107)
        at org.openqa.selenium.remote.ErrorHandler.<init>(ErrorHandler.java:73)
        at org.openqa.selenium.remote.ErrorHandler.<init>(ErrorHandler.java:64)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:87)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:170)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:159)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:148)
  ...
```
My guess is that wdm is using Selenium 2.53.1 

```
> mvn dependency:tree
[INFO] +- org.seleniumhq.selenium:selenium-java:jar:3.0.0-beta4:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-chrome-driver:jar:3.0.0-beta4:compile
[INFO] |  |  \- org.seleniumhq.selenium:selenium-remote-driver:jar:3.0.0-beta4:compile
[INFO] |  |     +- cglib:cglib-nodep:jar:3.2.4:compile
[INFO] |  |     +- org.apache.commons:commons-exec:jar:1.3:compile
[INFO] |  |     +- org.apache.httpcomponents:httpclient:jar:4.5.2:compile
[INFO] |  |     |  \- org.apache.httpcomponents:httpcore:jar:4.4.4:compile
[INFO] |  |     +- org.apache.httpcomponents:httpmime:jar:4.5.2:compile
[INFO] |  |     +- net.java.dev.jna:jna:jar:4.1.0:compile
[INFO] |  |     \- net.java.dev.jna:jna-platform:jar:4.1.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-edge-driver:jar:3.0.0-beta4:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-firefox-driver:jar:3.0.0-beta4:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-ie-driver:jar:3.0.0-beta4:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-opera-driver:jar:3.0.0-beta4:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-safari-driver:jar:3.0.0-beta4:compile
[INFO] |  |  \- io.netty:netty:jar:3.5.7.Final:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-support:jar:3.0.0-beta4:compile
[INFO] |  \- com.codeborne:phantomjsdriver:jar:1.3.0:compile
...
[INFO] \- io.github.bonigarcia:webdrivermanager:jar:1.4.9:compile
[INFO]    +- com.typesafe:config:jar:1.2.1:compile
[INFO]    +- org.apache.commons:commons-lang3:jar:3.4:compile
[INFO]    +- org.rauschig:jarchivelib:jar:0.7.1:compile
[INFO]    |  \- org.apache.commons:commons-compress:jar:1.9:compile
[INFO]    +- org.jsoup:jsoup:jar:1.9.2:compile
[INFO]    +- org.seleniumhq.selenium:selenium-api:jar:2.53.1:compile
[INFO]    \- org.seleniumhq.selenium:htmlunit-driver:jar:2.20:compile
[INFO]       +- net.sourceforge.htmlunit:htmlunit:jar:2.20:compile
[INFO]       |  +- xalan:xalan:jar:2.7.2:compile
[INFO]       |  |  \- xalan:serializer:jar:2.7.2:compile
[INFO]       |  +- commons-codec:commons-codec:jar:1.10:compile
[INFO]       |  +- net.sourceforge.htmlunit:htmlunit-core-js:jar:2.17:compile
[INFO]       |  +- xerces:xercesImpl:jar:2.11.0:compile
[INFO]       |  |  \- xml-apis:xml-apis:jar:1.4.01:compile
[INFO]       |  +- net.sourceforge.nekohtml:nekohtml:jar:1.9.22:compile
[INFO]       |  +- net.sourceforge.cssparser:cssparser:jar:0.9.18:compile
[INFO]       |  |  \- org.w3c.css:sac:jar:1.3:compile
[INFO]       |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO]       |  \- org.eclipse.jetty.websocket:websocket-client:jar:9.2.15.v20160210:compile
[INFO]       |     +- org.eclipse.jetty:jetty-util:jar:9.2.15.v20160210:compile
[INFO]       |     +- org.eclipse.jetty:jetty-io:jar:9.2.15.v20160210:compile
[INFO]       |     \- org.eclipse.jetty.websocket:websocket-common:jar:9.2.15.v20160210:compile
[INFO]       |        \- org.eclipse.jetty.websocket:websocket-api:jar:9.2.15.v20160210:compile
```

Because Selenium 3 is coming up and [beta 4 could be the official release](https://seleniumhq.wordpress.com/2016/10/04/selenium-3-is-coming/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+Selenium+%28The+Official+Selenium+Blog%29) I think this has to be solved.

**Comment by bonigarcia** [comment]
Please use version 1.4.10, just released.
