### ISSUE TITLE
COMPILATION ERROR : package io.github.bonigarcia.wdm does not exist

### ISSUE THREAD

**Issue by vishruth143** [bonigarcia/webdrivermanager#251]
Hi,

When I build my maven project with **mvn pre-clean clean install** command

I get the below COMPILATION ERROR.

**Note:** I'm able to run the tests individually using the TestNG

**Test Details:**
**Selenium Version:** 3.14.0
**Maven Version:** 3.5.2
**webdrivermanager Version:** 3.0.0
**Browser:** Internet explorer 11
**OS:** Windows 7 Enterprise 64-Bit

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /C:/Selenium Automation Framework/awseleniumtestautomation/src/main/java/com/tcs/saf/base/WebDriverFactory.java:[18,32] package io.github.bonigarcia.wdm does not exist
[ERROR] /C:/Selenium Automation Framework/awseleniumtestautomation/src/main/java/com/tcs/saf/base/WebDriverFactory.java:[38,33] cannot find symbol
  symbol:   variable WebDriverManager
  location: class com.tcs.saf.base.WebDriverFactory
[ERROR] /C:/Selenium Automation Framework/awseleniumtestautomation/src/main/java/com/tcs/saf/base/WebDriverFactory.java:[55,33] cannot find symbol
  symbol:   variable WebDriverManager
  location: class com.tcs.saf.base.WebDriverFactory
[ERROR] /C:/Selenium Automation Framework/awseleniumtestautomation/src/main/java/com/tcs/saf/base/WebDriverFactory.java:[66,33] cannot find symbol
  symbol:   variable WebDriverManager
  location: class com.tcs.saf.base.WebDriverFactory
[ERROR] /C:/Selenium Automation Framework/awseleniumtestautomation/src/main/java/com/tcs/saf/base/WebDriverFactory.java:[86,25] cannot find symbol
  symbol:   variable WebDriverManager
  location: class com.tcs.saf.base.WebDriverFactory
[INFO] 5 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.011 s
[INFO] Finished at: 2018-09-22T15:32:51-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project AW.Nxt_TCS_OSAF_SeleniumAutomationFramework: Compilation failure: Compilation failure: 
[ERROR] /C:/Selenium Automation Framework/awseleniumtestautomation/src/main/java/com/tcs/saf/base/WebDriverFactory.java:[18,32] package io.github.bonigarcia.wdm does not exist
[ERROR] /C:/Selenium Automation Framework/awseleniumtestautomation/src/main/java/com/tcs/saf/base/WebDriverFactory.java:[38,33] cannot find symbol
[ERROR]   symbol:   variable WebDriverManager
[ERROR]   location: class com.tcs.saf.base.WebDriverFactory
[ERROR] /C:/Selenium Automation Framework/awseleniumtestautomation/src/main/java/com/tcs/saf/base/WebDriverFactory.java:[55,33] cannot find symbol
[ERROR]   symbol:   variable WebDriverManager
[ERROR]   location: class com.tcs.saf.base.WebDriverFactory
[ERROR] /C:/Selenium Automation Framework/awseleniumtestautomation/src/main/java/com/tcs/saf/base/WebDriverFactory.java:[66,33] cannot find symbol
[ERROR]   symbol:   variable WebDriverManager
[ERROR]   location: class com.tcs.saf.base.WebDriverFactory
[ERROR] /C:/Selenium Automation Framework/awseleniumtestautomation/src/main/java/com/tcs/saf/base/WebDriverFactory.java:[86,25] cannot find symbol
[ERROR]   symbol:   variable WebDriverManager
[ERROR]   location: class com.tcs.saf.base.WebDriverFactory
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by savitaHpatil** [comment]
Changed scope to 'compile' from 'test' but still same error/issue.

**Comment by micro1964** [comment]
I had to change the version to 5.1.0 to solve the issue

**Comment by ErnestoPasillas** [comment]
same error I was using 4.4.3 and when I update to 5.1.1 error still

**Comment by aartiwalia** [comment]
Hi,
 I am using the 5.8.0 version and still getting 'WendriverManger cannot be resolevd to a type error. 
<dependency>
    <groupId>io.github.bonigarcia</groupId>
    <artifactId>webdrivermanager</artifactId>
    <version>5.8.0</version>
   
</dependency>
