### ISSUE TITLE
NoClassDefFound org/apache/http/auth/Credentials

### ISSUE THREAD

**Issue by ishwar6789** [bonigarcia/webdrivermanager#94]
When I try to create a new chromedriver, I am getting the above error, i can see the same error even when i run the unit tests in the project. 
Tests in error:
  ChromeTest.setupTest:40 » NoClassDefFound org/apache/http/auth/Credentials
  ChromeVersionTest.initializationError »  No runnable methods
  EdgeTest.setupTest:46 » NoClassDefFound org/apache/http/auth/Credentials
  EdgeVersionTest.initializationError »  No runnable methods
  FirefoxVersionTest.initializationError »  No runnable methods
  IExplorerTest.setupTest:47 » NoClassDefFound org/apache/http/auth/Credentials
  IExplorerVersionTest.initializationError »  No runnable methods
  OperaVersionTest.initializationError »  No runnable methods
  PhantomJsTest.setupTest:53 » NoClassDefFound org/apache/http/auth/Credentials
  PhantomJsVersionTest.initializationError »  No runnable methods
Complete trace:
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.907 sec <<< FAILURE! - in io.github.bonigarcia.wdm.test.ChromeTest
test(io.github.bonigarcia.wdm.test.ChromeTest)  Time elapsed: 0.083 sec  <<< ERROR!
java.lang.NoClassDefFoundError: org/apache/http/auth/Credentials
        at io.github.bonigarcia.wdm.test.ChromeTest.setupTest(ChromeTest.java:40)
Caused by: java.lang.ClassNotFoundException: org.apache.http.auth.Credentials
        at io.github.bonigarcia.wdm.test.ChromeTest.setupTest(ChromeTest.java:40)

anyideas??
I am running the maven test on a windows machine,

**Comment by ishwar6789** [comment]
I found the issues there is some issue with selenium 3 i guess the http jars are not getting referenced correctly, works fine with selenium 2.53.1.  please close the defect . thanks guys !!!

**Comment by irisida** [comment]
Is there any update to this saga? 
I've just been playing with 3.5.3 and I have the same error as above and when going back to 2.53.1 the same rudimentary example works fine.

If it's just a case of adding an extra dependency in could you let me know which as I seem to be going in classpath-hell circles. 

Thanks
