### ISSUE TITLE
Module version 5.4.1+ cannot be used with Java 1.8 anymore

### ISSUE THREAD

**Issue by mykola-mokhnach** [bonigarcia/webdrivermanager#1092]
**Description of the problem**: Recently we got notified about the new module update has been released, although it cannot be used because our project still supports Java 1.8 and the module class seems to be compiled for Java11. I would expect the major module version bumped for such type of change.

**Browser and version**:  non applicable

**Operating system**:  all

**WebDriverManager version**:  5.4.1

**WebDriverManager call**:  `import static io.github.bonigarcia.wdm.WebDriverManager.chromedriver;`

**WebDriverManager traces**: 

https://github.com/appium/java-client/actions/runs/5644148044/job/15287352397?pr=1966

**Error log**: 

```
8 actionable tasks: 7 executed, 1 up-to-date
  bad class file: /Users/runner/.gradle/caches/modules-2/files-2.1/io.github.bonigarcia/webdrivermanager/5.4.1/442d8a6a6e5ad6aad7e1ac281be5845ad13b6ff0/webdrivermanager-5.4.1.jar(io/github/bonigarcia/wdm/WebDriverManager.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```

**Comment by bonigarcia** [comment]
Sorry for the inconvenience. I did this bump since WebDriverManager is connected to Selenium, and they announced that [as of September 2023, the minimum Java version will be Java 11](https://www.selenium.dev/blog/2023/java-8-support/). Strictly, this change would require a change version to WebDriverManager 6. But WebDriverManager, like Selenium, does not follow a strict semantic version schema. So I decided to bump it to 5.4.1 and announce it on the [changelog](https://github.com/bonigarcia/webdrivermanager/blob/master/CHANGELOG.md) and [Twitter](https://twitter.com/boni_gg/status/1671790656690298880). 

But the good thing about this kind of project is that it is open source. That means you can use it or not, as [Selenide](https://selenide.org/2023/08/02/selenide-6.17.0/) has already done. And even better, now we have Selenium Manager to manage drivers automatically. I know Selenium Manager very well because I am the one developing the Rust logic. I think WebDriverManager still is a good tool used by many, and for that, I'm still investing my leisure time in maintaining it. Moreover, it has additional features not available in Selenium Manager (e.g., auto-managed dockerized browser or monitoring). But for strictly automated driver manager, you can switch to Selenium Manager. Although it is still in beta, it is behaving quite well.

The alternative to keep using WebDriverManager is to bump to Java 11. In any case, if you plan to use the latest version of Selenium, you will need to do it by next month.

**Comment by adrian-herscu** [comment]
>> I did this bump since WebDriverManager is connected to Selenium

I could not find any real good thing in Selenium 4, on the other hand it requires upgrading to Java 11 and change test code...
Anyway, after upgrading WebDriverManager to 5.3.3 it suddenly works with Chrome 116 :)

**Comment by bonigarcia** [comment]
I've been thinking about this. To provide a solution to those that cannot bump to Java 11, I  released WebDriverManager 5.5.0, compiled with Java 8.

In any case, my personal opinion is that Java 8 is already an ancient version, and I recommend using at least Java 11+ as soon as possible.

**Comment by nad333m** [comment]
@bonigarcia . Truly appreciate your effort to release a version for java8. Great help!!

**Comment by SamuelRussellP** [comment]
> I've been thinking about this. To provide a solution to those that cannot bump to Java 11, I released WebDriverManager 5.5.0, compiled with Java 8.
> 
> In any case, my personal opinion is that Java 8 is already an ancient version, and I recommend using at least Java 11+ as soon as possible.

I am currently using webdrivermanager version 5.9.1 and also using this selenium-java dependency:

        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.22.0</version>
        </dependency>

Which will result to this error:

        java.lang.NoSuchMethodError: 'java.nio.file.Path org.openqa.selenium.internal.Require$PathStateChecker.isExecutable()'
	at org.openqa.selenium.remote.service.DriverFinder.getBinaryPaths(DriverFinder.java:118)
	at org.openqa.selenium.remote.service.DriverFinder.getDriverPath(DriverFinder.java:55)
	at org.openqa.selenium.chrome.ChromeDriver.generateExecutor(ChromeDriver.java:99)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:83)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:72)
	at org.hyrdnewcompany.driver.CustomDriver.newDriver(CustomDriver.java:21)
	
	
Any idea whether this is just incompatibality issue or not? @bonigarcia

**Comment by adrian-herscu** [comment]
> > I've been thinking about this. To provide a solution to those that cannot bump to Java 11, I released WebDriverManager 5.5.0, compiled with Java 8.
> > In any case, my personal opinion is that Java 8 is already an ancient version, and I recommend using at least Java 11+ as soon as possible.
> 
> I am currently using webdrivermanager version 5.9.1 and also using this selenium-java dependency:
> 
> ```
>     <dependency>
>         <groupId>org.seleniumhq.selenium</groupId>
>         <artifactId>selenium-java</artifactId>
>         <version>4.22.0</version>
>     </dependency>
> ```
> 
> Which will result to this error:
> 
> ```
>     java.lang.NoSuchMethodError: 'java.nio.file.Path org.openqa.selenium.internal.Require$PathStateChecker.isExecutable()'
> at org.openqa.selenium.remote.service.DriverFinder.getBinaryPaths(DriverFinder.java:118)
> at org.openqa.selenium.remote.service.DriverFinder.getDriverPath(DriverFinder.java:55)
> at org.openqa.selenium.chrome.ChromeDriver.generateExecutor(ChromeDriver.java:99)
> at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88)
> at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:83)
> at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:72)
> at org.hyrdnewcompany.driver.CustomDriver.newDriver(CustomDriver.java:21)
> ```
> 
> Any idea whether this is just incompatibality issue or not? @bonigarcia

I finally migrated to Java 11 and switched to Selenium 4:

```xml
<dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-java</artifactId>
      <version>4.19.1</version>
    </dependency>

    <dependency>
      <groupId>io.github.bonigarcia</groupId>
      <artifactId>webdrivermanager</artifactId>
      <version>5.7.0</version>
    </dependency>
```

For me, this combo works.

**Comment by NadiaUoM** [comment]
ests run: 8, Failures: 1, Errors: 0, Skipped: 7, Time elapsed: 1.966 sec <<< FAILURE! - in TestSuite
driverInitilization(uk.ac.manchester.its.media.opencast.OpencastSelenium)  Time elapsed: 1.678 sec  <<< FAILURE!
java.lang.NoSuchMethodError: 'java.nio.file.Path org.openqa.selenium.internal.Require$PathStateChecker.isExecutable()'
        at org.openqa.selenium.remote.service.DriverFinder.getBinaryPaths(DriverFinder.java:118)
        at org.openqa.selenium.remote.service.DriverFinder.getDriverPath(DriverFinder.java:55)
        at org.openqa.selenium.chrome.ChromeDriver.generateExecutor(ChromeDriver.java:99)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:83)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:72)
        at uk.ac.manchester.its.media.opencast.SetUp.getDriver(SetUp.java:50)

Getting this error with Java 17.

i am using selenium-java 4.19.1 and webdrivermanger 5.7.0

can someone tell me the what the issue is here
